### PR TITLE
Quality of life changes (Alpha Strike)

### PR DESCRIPTION
**Pull request by 1VinceP**
This adds some small QoL changes including:
- reduce padding on mobile to improve readability
- on AS search page: allow sorting by Name or by PV
- on AS search table: allow horizontal scrolling to enable vertical phone usage
- on AS unit rows: display MV value

My typescript and React class components are a bit rusty, let me know if there's anything you'd like me to tidy up.

image
image

### CODE REVIEW

**Comment by 1VinceP** [comment]
@jdgwf @Stew-rt Hey! Hope all is well. I know life gets busy, but I was wondering if you might have some time to review this PR?

**Comment by Stew-rt** [comment]
Hey @1VinceP, great work, but I'm afraid this isn't my repository.
The only thing i can say from experience is jdgwf will get to this, and is very positive about PRs against his project, but might take a little while due to real life.

**Comment by jdgwf** [comment]
Heck yeah I'll take a look at it. My last chemo was Wed->Fri so I'm still a little fatigued. This weekend we'll be going to MD Anderson in Houston to get my PET/CT and MRI scans to see what the next step is.

My cancer markers according to the Signatera blood tests are WAY down. So things are looking good so far despite my fatigue.

Thank you for looking into this project and sending a PR. I'll get to it soon :)

**Review by jdgwf — APPROVED** [review]

**Comment by 1VinceP** [comment]
> Hey @1VinceP, great work, but I'm afraid this isn't my repository. The only thing i can say from experience is jdgwf will get to this, and is very positive about PRs against his project, but might take a little while due to real life.

Gotcha, thanks for the info!

> Heck yeah I'll take a look at it. My last chemo was Wed->Fri so I'm still a little fatigued. This weekend we'll be going to MD Anderson in Houston to get my PET/CT and MRI scans to see what the next step is.
> 
> My cancer markers according to the Signatera blood tests are WAY down. So things are looking good so far despite my fatigue.
> 
> Thank you for looking into this project and sending a PR. I'll get to it soon :)

Oh yeah that's awesome, so great to hear!
Sorry for interrupting your day, I got excited about an Alpha Strike game coming up tonight and got ahead of my manners. Best wishes to you and your family!

**Comment by jdgwf** [comment]
I read absolutely nothing wrong with your manners... I'm pretty laid back these days. As @1VinceP mentioned I'm pretty crazy busy with multiple projects, fighting the big C, and  working full time (which with Chemo is a feat upon itself).

**Pull request merged**
